### ISSUE TITLE
emit-1.0.tar.gz and run-1.2.tar.gz

### ISSUE THREAD

**Issue by serge2016** [FDA/precisionFDA#3]
Hello!

Could you help me, please, with downloading this files:
```
# Download helper executables
url https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
```
https://github.com/FDA/precisionFDA/blob/master/app/models/app.rb#L192

`ubuntu-signing-key.gpg` is also not available:
```
curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add - 
```

**Comment by pamelladnanexus** [comment]
> Hello!
> 
> Could you help me, please, with downloading this files:
> 
> ```
> # Download helper executables
> url https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
> curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
> ```
> 
> https://github.com/FDA/precisionFDA/blob/master/app/models/app.rb#L192
> 
> `ubuntu-signing-key.gpg` is also not available:
> 
> ```
> curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add - 
> ```

Please use 
```curl https://precision.fda.gov/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions```
```curl https://precision.fda.gov/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions```

Also use 
```curl https://dnanexus-sdk.s3.amazonaws.com/apt/ubuntu-signing-key.gpg  | apt-key add - ```
